# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SRCiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
#        config.build_settings['CODE_SIGN_STYLE'] = 'NO'
#        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
#        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#      config.build_settings['PROVISIONING_PROFILE'] = ''
#      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
#      end
#    end
#  end
  # Pods for SRCiOS
  pod 'WebViewJavascriptBridge', '~> 6.0'

end
